# fly.toml app configuration file generated for sync-shopify-stores-inventory on 2023-12-29T19:17:40+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#


# SECRETS FOR THIS SHOP
# flyctl secrets set SHOPIFY_API_SECRET=ef48c6a0360231b112ce5cbb3a0e5e93 DB_NAME=sync-stores DB_CONN_STRING=mongodb+srv://danperlmanprog:YXKnG8S0NE4kVapI@inventory-app.strew6i.mongodb.net/sync-stores
# DEPLOY COMMAND
# flyctl deploy --build-arg SHOPIFY_API_KEY=e5b16d3ad2e5ae5575aa28d4046eed8b --remote-only

app = "sync-shopify-stores-inventory"
primary_region = "sin"

[env]
  HOST = "https://sync-shopify-stores-inventory.fly.dev"
  PORT = "8081"
  SCOPES = "write_products,write_orders,write_inventory"
  SHOPIFY_API_KEY = "e5b16d3ad2e5ae5575aa28d4046eed8b"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
