# fly.toml app configuration file generated for sync-shopify-stores-inventory-2 on 2024-01-04T21:07:07+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

# SECRETS FOR THIS SHOP
# flyctl secrets set SHOPIFY_API_SECRET=aa6790f4f11e7a90d4ec998d388f1b83 DB_NAME=sync-stores DB_CONN_STRING=mongodb+srv://danperlmanprog:YXKnG8S0NE4kVapI@inventory-app.strew6i.mongodb.net/sync-stores
# DEPLOY COMMAND
# flyctl deploy --build-arg SHOPIFY_API_KEY=2ca0641c71fbb3050e35232b491bc09b --remote-only

app = "sync-shopify-stores-inventory-2"
primary_region = "sin"

[env]
  HOST = "https://sync-shopify-stores-inventory-2.fly.dev"
  PORT = "8081"
  SCOPES = "write_products,write_orders,write_inventory"
  SHOPIFY_API_KEY = "2ca0641c71fbb3050e35232b491bc09b"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
