# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sync-stores-ahsan"
client_id = "b6269234e93c392fce57f35fcf1f938d"
application_url = "https://excel-reliable-dates-cancer.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_orders,write_inventory"

[auth]
redirect_urls = [
  "https://excel-reliable-dates-cancer.trycloudflare.com/auth/callback",
  "https://excel-reliable-dates-cancer.trycloudflare.com/auth/shopify/callback",
  "https://excel-reliable-dates-cancer.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cocomo001.myshopify.com"
