# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "sync-stores"
client_id = "a67550ec334a05ecc95c29af0bc620e9"
application_url = "https://asset-happiness-smithsonian-nv.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://asset-happiness-smithsonian-nv.trycloudflare.com/auth/callback",
  "https://asset-happiness-smithsonian-nv.trycloudflare.com/auth/shopify/callback",
  "https://asset-happiness-smithsonian-nv.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-659.myshopify.com"
